// IGLOBAL Actions
export const CHANGE_SOURCE = 'CHANGE_SOURCE';
export const CHANGE_LIBRARY = 'CHANGE_LIBRARY';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const UPDATE_EDITOR_VALUE = 'UPDATE_EDITOR_VALUE';




// Collab Editing
export const INIT_INVITE = 'INIT_INVITE';
export const INVALID_EDITOR_SESSION_ID = 'INVALID_EDITOR_SESSION_ID';
export const FINISH_INVITE = 'FINISH_INVITE';
export const SET_EDITOR_SESSION_ID = 'SET_EDITOR_SESSION_ID';
export const SET_WEBSOCKET_STATUS = 'SET_WEBSOCKET_STATUS';