export enum SideContentType {
  autograder = "autograder",
  briefing = "briefing",
  chat = "chat",
  dataVisualiser = "data_visualiser",
  editorGrading = "editor_grading",
  editorAutograder = "editor_autograder",
  editorBriefing = "editor_briefing",
  editorGlobalDeployment = "editor_global_deployment",
  editorGlobalGraderDeployment = "editor_global_grader_deployment",
  editorLocalDeployment = "editor_local_deployment",
  editorLocalGraderDeployment = "editor_local_grader_deployment",
  editorManageQuestion = "editor_manage_question",
  editorQuestionOverview = "editor_question_overview",
  editorQuestionTemplate = "editor_question_template",
  envVisualiser = "env_visualiser",
  grading = "grading",
  introduction = "introduction",
  inspector = "inspector",
  questionOverview = "question_overview",
  substVisualizer = "subst_visualiser",
  toneMatrix = "tone_matrix"
}
